### ISSUE TITLE
How can I install the plugin ?

### ISSUE THREAD

**Issue by nicolinuxfr** [BenjaminMedia/wp-focal-point#8]
Hello

I tried to install the plugin on my blog, but I have this PHP fatal error after installation : 

```
[29-Jun-2020 07:47:30 UTC] PHP Fatal error:  Uncaught Error: Class 'Bonnier\WP\FocalPoint\FocalPoint' not found in /var/www/voiretmanger.fr/wp-content/plugins/wp-focal-point/wp-focal-point.php:17
Stack trace:
#0 /var/www/voiretmanger.fr/wp-includes/class-wp-hook.php(287): register_focal_point_plugin()
#1 /var/www/voiretmanger.fr/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 /var/www/voiretmanger.fr/wp-includes/plugin.php(478): WP_Hook->do_action()
#3 /var/www/voiretmanger.fr/wp-settings.php(403): do_action()
#4 /var/www/voiretmanger.fr/wp-config.php(170): require_once('/var/www/voiret...')
#5 /var/www/voiretmanger.fr/wp-load.php(37): require_once('/var/www/voiret...')
#6 /var/www/voiretmanger.fr/wp-blog-header.php(13): require_once('/var/www/voiret...')
#7 /var/www/voiretmanger.fr/index.php(17): require('/var/www/voiret...')
#8 {main}
  thrown in /var/www/voiretmanger.fr/wp-content/plugins/wp-focal-point/wp-focal-point.php on line 17
```

I did the `composer install` needed, but removed the wordpress downloading part, since I was adding the plugin to an existing site. 

Is there something missing in my installation ? 

Thanks !

**Comment by pimpiet** [comment]
This works form me.

Add "require_once __DIR__ . '/vendor/autoload.php';"
to the top of "wp-focal-point.php" file.

**Comment by nicolinuxfr** [comment]
Thanks for your help ! 👍

I managed to activate the plugin using this version in the file : 

`require_once(__DIR__ . '/vendor/autoload.php');`.
